"""Add reset_token column to user table

Revision ID: 363075e139c1
Revises: 273adde4fb4a
Create Date: 2025-03-21 11:16:12.168069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363075e139c1'
down_revision = '273adde4fb4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###
